# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20161105_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='websites',
            field=models.ManyToManyField(related_name='websites', to='websites.Website'),
        ),
    ]
